FROM centos:7 AS builder

RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum install --downloadonly --downloaddir=/data/tools socat nfs-tools socat telnet \
    && createrepo /data/tools \
    && tar zcvf /data/tools.tar.gz /data/tools \
    && rm -rf /data/tools \
    && rm -rf /var/cache/yum
    
From alpine
# copy file from the first stage
COPY --from=builder /data/tools.tar.gz /tools.tar.gz
