FROM centos:7 AS builder
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum install https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm -y \
    && rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org \ 
    && yum -y --enablerepo=elrepo-kernel install --downloadonly --downloaddir=/data/kernel-ml kernel-ml.x86_64 kernel-ml-devel.x86_64\
    && createrepo /data/kernel-ml \
    && tar zcvf /data/kernel-ml.tar.gz /data/kernel-ml \
    && rm -rf /data/kernel-ml \
    && rm -rf /var/cache/yum
    
From alpine
# copy file from the first stage
COPY --from=builder /data/kernel-ml.tar.gz /kernel-ml.tar.gz
