FROM centos:7 AS builder

ENV SOFT_NAME=keepalived

RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum install --downloadonly --downloaddir=/data/$SOFT_NAME $SOFT_NAME \
    && createrepo /data/$SOFT_NAME \
    && tar zcvf /data/$SOFT_NAME.tar.gz /data/$SOFT_NAME \
    && rm -rf /data/$SOFT_NAME \
    && rm -rf /var/cache/yum
    
From scratch

ENV SOFT_NAME=keepalived
# copy file from the first stage
COPY --from=builder /data/$SOFT_NAME.tar.gz /$SOFT_NAME.tar.gz
